/* Generated by Yosys 0.68+136 (git sha1 c30457480, Release, GNU /usr/bin/c++ 13.3.0) */

module mux_2to1(I0, I1, S, Y);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input S;
  wire S;
  output Y;
  wire Y;
  MUX2_X1 _0_ (
    .A(I0),
    .B(I1),
    .S(S),
    .Z(Y)
  );
endmodule
