/* Generated by Yosys 0.68+136 (git sha1 c30457480, Release, GNU /usr/bin/c++ 13.3.0) */

module decoder_2to4(A, B, Y0, Y1, Y2, Y3);
  input A;
  wire A;
  input B;
  wire B;
  output Y0;
  wire Y0;
  output Y1;
  wire Y1;
  output Y2;
  wire Y2;
  output Y3;
  wire Y3;
  wire _0_;
  INV_X1 _1_ (
    .A(B),
    .ZN(_0_)
  );
  NOR2_X1 _2_ (
    .A1(_0_),
    .A2(A),
    .ZN(Y1)
  );
  NOR2_X1 _3_ (
    .A1(B),
    .A2(A),
    .ZN(Y0)
  );
  AND2_X1 _4_ (
    .A1(B),
    .A2(A),
    .ZN(Y3)
  );
  AND2_X1 _5_ (
    .A1(_0_),
    .A2(A),
    .ZN(Y2)
  );
endmodule
