/* Generated by Yosys 0.68+136 (git sha1 c30457480, Release, GNU /usr/bin/c++ 13.3.0) */

module mux_4to1(I0, I1, I2, I3, S0, S1, Y);
  input I0;
  wire I0;
  input I1;
  wire I1;
  input I2;
  wire I2;
  input I3;
  wire I3;
  input S0;
  wire S0;
  input S1;
  wire S1;
  output Y;
  wire Y;
  wire _0_;
  wire _1_;
  MUX2_X1 _2_ (
    .A(I2),
    .B(I3),
    .S(S0),
    .Z(_0_)
  );
  MUX2_X1 _3_ (
    .A(I0),
    .B(I1),
    .S(S0),
    .Z(_1_)
  );
  MUX2_X1 _4_ (
    .A(_1_),
    .B(_0_),
    .S(S1),
    .Z(Y)
  );
endmodule
