/* Generated by Yosys 0.68+136 (git sha1 c30457480, Release, GNU /usr/bin/c++ 13.3.0) */

module decoder_2to4(A, B, Y0, Y1, Y2, Y3);
  input A;
  wire A;
  input B;
  wire B;
  output Y0;
  wire Y0;
  output Y1;
  wire Y1;
  output Y2;
  wire Y2;
  output Y3;
  wire Y3;
  wire _0_;
  wire _1_;
  assign Y0 = _0_ & _1_;
  assign Y1 = _0_ & B;
  assign Y2 = A & _1_;
  assign Y3 = A & B;
  assign _0_ = ~ A;
  assign _1_ = ~ B;
endmodule
